---
- name: Deploy Scientific Calculator Container
  hosts: localhost
  become: yes
  gather_facts: no
  tasks:
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: rakshit910/scientific_calculator
        tag: latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: scientific_calculator
        image: rakshit910/scientific_calculator:latest
        state: started
        restart_policy: always